export const healthPolicyCopy = {
  en: {
    more: "Next records",
    recordDate: "Record verified signing date",
    renewal: "Your health declaration expires within 30 days. Please renew it before expiry.",
    parentRenewal: "A participant you sign for needs her declaration renewed within 30 days.",
    renew: "Renew declaration",
    signedOn: "Certificate signing date (verify on the document)",
    retention: "Record retention review",
    load: "Load records needing review",
    empty: "No records need retention review.",
    reference: "Declaration reference",
    held: "On hold",
    reviewRequired: "Review required — no automatic deletion",
    hold: "Place hold",
    release: "Clear hold",
    confirmed: "I confirm this record and the hold decision. Clearing a hold does not delete it.",
    incident: "Incident",
    claim: "Claim",
    other_review: "Other review",
    reason: "Reason",
    done: "Hold decision recorded.",
    error: "The request could not be completed. Please retry.",
    certificateDateMissing: "Certificate signing date needs review",
  },
  he: {
    more: "הרשומות הבאות",
    recordDate: "שמירת תאריך חתימה מאומת",
    renewal: "תוקף הצהרת הבריאות יפוג בתוך 30 יום. יש לחדש אותה לפני פקיעת התוקף.",
    parentRenewal: "יש לחדש בתוך 30 יום הצהרה של מתאמנת שעבורה אתם חותמים.",
    renew: "חידוש ההצהרה",
    signedOn: "תאריך חתימת האישור הרפואי (יש לוודא במסמך)",
    retention: "בדיקת שמירת רשומות",
    load: "טעינת רשומות לבדיקה",
    empty: "אין רשומות הממתינות לבדיקת שמירה.",
    reference: "מזהה ההצהרה",
    held: "השמירה הוקפאה למחיקה",
    reviewRequired: "נדרשת בדיקה — אין מחיקה אוטומטית",
    hold: "מניעת מחיקה",
    release: "ביטול מניעת מחיקה",
    confirmed: "בדקתי את הרשומה ואני מאשר/ת את ההחלטה. ביטול ההקפאה אינו מוחק את הרשומה.",
    incident: "אירוע",
    claim: "תביעה",
    other_review: "בדיקה אחרת",
    reason: "סיבה",
    done: "ההחלטה נשמרה.",
    error: "לא ניתן להשלים את הבקשה. נסו שוב.",
    certificateDateMissing: "יש לבדוק את תאריך חתימת האישור הרפואי",
  },
  ar: {
    more: "السجلات التالية",
    recordDate: "تسجيل تاريخ التوقيع المتحقق منه",
    renewal: "تنتهي صلاحية إقرارك الصحي خلال 30 يومًا. يرجى تجديده قبل انتهاء الصلاحية.",
    parentRenewal: "يجب تجديد إقرار مشتركة توقّع عنها خلال 30 يومًا.",
    renew: "تجديد الإقرار",
    signedOn: "تاريخ توقيع الشهادة الطبية (تحقق منه في المستند)",
    retention: "مراجعة الاحتفاظ بالسجلات",
    load: "تحميل السجلات للمراجعة",
    empty: "لا توجد سجلات تحتاج مراجعة الاحتفاظ.",
    reference: "مرجع الإقرار",
    held: "الحذف معلّق",
    reviewRequired: "المراجعة مطلوبة — لا يوجد حذف تلقائي",
    hold: "تعليق الحذف",
    release: "رفع تعليق الحذف",
    confirmed: "أؤكد السجل وقرار التعليق. رفع التعليق لا يحذف السجل.",
    incident: "حادث",
    claim: "مطالبة",
    other_review: "مراجعة أخرى",
    reason: "السبب",
    done: "تم تسجيل القرار.",
    error: "تعذر إكمال الطلب. يرجى المحاولة مجددًا.",
    certificateDateMissing: "تاريخ توقيع الشهادة يحتاج إلى مراجعة",
  },
};
