export const clinicalCopy = {
  en: {
    yes: "Yes",
    no: "No",
    na: "Not applicable",
    choose: "Participant",
    draft: "Draft for review — use fictional answers only during testing.",
    privacy: "Health-data privacy notice",
    submit: "Confirm and submit declaration",
    retry: "Retry submission",
    error:
      "This step could not be completed. Please try again. Unconfirmed submissions keep the same answers and request number.",
    loading: "Loading…",
    missing: "Please complete your declaration.",
    valid: "Your declaration is complete.",
    requires_medical_document:
      "A medical certificate is required before new bookings are available.",
    pending_review:
      "Your medical certificate is waiting for review. Uploading a file does not approve it.",
    expired: "Your declaration has expired. Please complete a new one.",
    superseded: "Please complete a new declaration.",
    copy: "Read my submitted declaration",
    change: "Report a health change",
    document: "Medical certificate",
    fileHelp:
      "Upload one PDF, JPG or PNG, up to 5 MB. Include only the certificate needed for this review.",
    upload: "Upload certificate",
    download: "Download certificate",
    downloadReady: "Save certificate",
    review: "Medical document review",
    reviewed:
      "I have reviewed this certificate and confirmed that it meets the studio’s approved requirements for this participant.",
    accept: "Accept certificate",
    reject: "Reject certificate",
    empty: "No certificates awaiting review.",
    submitted: "Submitted",
    version: "Form version",
    back: "Back to declaration",
    saved: "Your declaration was received. No booking or charge was made.",
    signer: "Signer confirmation",
  },
  he: {
    yes: "כן",
    no: "לא",
    na: "לא רלוונטי",
    choose: "מתאמנת",
    draft: "טיוטה לבדיקה — בזמן הבדיקה יש להשתמש בתשובות בדיוניות בלבד.",
    privacy: "הודעת פרטיות למידע בריאותי",
    submit: "אישור ושליחת ההצהרה",
    retry: "ניסיון שליחה נוסף",
    error: "לא ניתן להשלים את השלב. נסו שוב. הגשה שלא אושרה שומרת על אותן תשובות ואותו מספר בקשה.",
    loading: "בטעינה…",
    missing: "יש למלא הצהרת בריאות.",
    valid: "הצהרת הבריאות הושלמה.",
    requires_medical_document: "נדרש אישור רפואי לפני שניתן לבצע הזמנות חדשות.",
    pending_review: "האישור הרפואי ממתין לבדיקה. העלאת קובץ אינה אישור לזכאות.",
    expired: "תוקף ההצהרה פג. יש למלא הצהרה חדשה.",
    superseded: "יש למלא הצהרה חדשה.",
    copy: "קריאת ההצהרה שנשלחה",
    change: "דיווח על שינוי בריאותי",
    document: "אישור רפואי",
    fileHelp:
      "ניתן להעלות קובץ PDF, JPG או PNG אחד, עד 5 MB. יש לכלול רק את האישור הדרוש לבדיקה זו.",
    upload: "העלאת אישור",
    download: "הורדת אישור",
    downloadReady: "שמירת אישור",
    review: "בדיקת מסמכים רפואיים",
    reviewed: "בדקתי את האישור ואישרתי שהוא עומד בדרישות המאושרות של הסטודיו עבור מתאמנת זו.",
    accept: "קבלת האישור",
    reject: "דחיית האישור",
    empty: "אין אישורים הממתינים לבדיקה.",
    submitted: "נשלח",
    version: "גרסת הטופס",
    back: "חזרה להצהרה",
    saved: "ההצהרה התקבלה. לא בוצעו הזמנה או חיוב.",
    signer: "אישור החותם",
  },
  ar: {
    yes: "نعم",
    no: "لا",
    na: "لا ينطبق",
    choose: "المشتركة",
    draft: "مسودة للمراجعة — استخدم إجابات افتراضية فقط أثناء الاختبار.",
    privacy: "إشعار خصوصية البيانات الصحية",
    submit: "تأكيد وإرسال الإقرار",
    retry: "إعادة محاولة الإرسال",
    error:
      "تعذر إكمال هذه الخطوة. حاول مجددًا. تحتفظ الطلبات غير المؤكدة بنفس الإجابات ورقم الطلب.",
    loading: "جارٍ التحميل…",
    missing: "يرجى إكمال الإقرار الصحي.",
    valid: "اكتمل الإقرار الصحي.",
    requires_medical_document: "يلزم تقديم شهادة طبية قبل إتاحة حجوزات جديدة.",
    pending_review: "شهادتك الطبية بانتظار المراجعة. رفع الملف لا يعني الموافقة عليه.",
    expired: "انتهت صلاحية الإقرار. يرجى إكمال إقرار جديد.",
    superseded: "يرجى إكمال إقرار جديد.",
    copy: "قراءة الإقرار المرسل",
    change: "الإبلاغ عن تغير صحي",
    document: "الشهادة الطبية",
    fileHelp:
      "ارفع ملف PDF أو JPG أو PNG واحدًا بحجم لا يتجاوز 5 MB. أرفق الشهادة اللازمة لهذه المراجعة فقط.",
    upload: "رفع الشهادة",
    download: "تنزيل الشهادة",
    downloadReady: "حفظ الشهادة",
    review: "مراجعة المستندات الطبية",
    reviewed: "راجعتُ هذه الشهادة وتأكدتُ من استيفائها متطلبات الاستوديو المعتمدة لهذه المشتركة.",
    accept: "قبول الشهادة",
    reject: "رفض الشهادة",
    empty: "لا توجد شهادات بانتظار المراجعة.",
    submitted: "تاريخ الإرسال",
    version: "إصدار النموذج",
    back: "العودة إلى الإقرار",
    saved: "تم استلام إقرارك. لم يُجرَ أي حجز أو خصم.",
    signer: "تأكيد الموقّع",
  },
};
