export const healthCopy = {
  en: {
    title: "Health declaration",
    unavailable: "Health declaration collection is not enabled. Contact the studio for support.",
    participant: "Participant",
    send: "Confirm and submit test",
    sending: "Saving…",
    retry: "Retry",
    consent: "Confirmation is required.",
    status: "Declaration status",
    copy: "Read submitted copy",
    change: "Report a change / submit a new version",
    upload: "Upload synthetic test document",
    review: "Authorized document review",
    read: "Read document",
    accept: "Accept reviewed test document",
    reject: "Reject test document",
    back: "Return to class — check availability and confirm booking",
    saved: "Server confirmed receipt. No booking or charge was made.",
    error: "Unable to complete this action. Your draft is still here. Retry safely.",
    required: "Complete your health declaration before booking.",
    pending: "Document review is pending. Upload alone does not approve eligibility.",
    choose: "Choose participant",
    guardian:
      "Only a verified parent or guardian may sign for a child. Each child needs a separate declaration.",
    draft: "Draft — not submitted",
    missing: "Missing",
    submitted: "Submitted",
    requires_medical_document: "Document required",
    pending_review: "Pending review",
    valid: "Valid eligibility (not a medical diagnosis)",
    expired: "Expired",
    superseded: "New declaration required",
    newVersion: "Start new test declaration",
    empty: "No documents awaiting review.",
    submittedAt: "Submitted",
    expiresAt: "Expires",
    language: "Language",
    fixture: "TEST ONLY — synthetic data only. No real health information.",
    download: "Download synthetic fixture",
    file: "Synthetic document (.txt only)",
    readCopy: "Submitted wording and test answer",
    history: "Submission history is retained securely. Corrections create a new version.",
    loading: "Loading…",
  },
  he: {
    title: "הצהרת בריאות",
    unavailable: "איסוף הצהרות הבריאות אינו מופעל. ניתן לפנות לסטודיו לתמיכה.",
    participant: "מתאמן/ת",
    send: "אישור ושליחת בדיקה",
    sending: "שומר…",
    retry: "ניסיון חוזר",
    consent: "נדרש אישור.",
    status: "מצב ההצהרה",
    copy: "קריאת עותק שהוגש",
    change: "דיווח על שינוי / הגשת גרסה חדשה",
    upload: "העלאת מסמך בדיקה סינתטי",
    review: "סקירת מסמכים מורשית",
    read: "קריאת מסמך",
    accept: "קבלת מסמך בדיקה שנבדק",
    reject: "דחיית מסמך בדיקה",
    back: "חזרה לשיעור — בדיקת מקום ואישור הזמנה",
    saved: "השרת אישר קבלה. לא נוצרה הזמנה ולא בוצע חיוב.",
    error: "לא ניתן להשלים פעולה זו. הטיוטה עדיין כאן. ניתן לנסות שוב בבטחה.",
    required: "יש להשלים הצהרת בריאות לפני ההזמנה.",
    pending: "ממתין לסקירת מסמך. העלאה לבדה אינה אישור זכאות.",
    choose: "בחירת מתאמן/ת",
    guardian: "רק הורה או אפוטרופוס מאומת רשאי לחתום עבור ילד. לכל ילד נדרשת הצהרה נפרדת.",
    draft: "טיוטה — טרם הוגשה",
    missing: "חסרה",
    submitted: "הוגשה",
    requires_medical_document: "נדרש מסמך",
    pending_review: "ממתין לסקירה",
    valid: "זכאות תקפה (לא אבחנה רפואית)",
    expired: "פג תוקף",
    superseded: "נדרשת הצהרה חדשה",
    newVersion: "התחלת הצהרת בדיקה חדשה",
    empty: "אין מסמכים הממתינים לסקירה.",
    submittedAt: "מועד הגשה",
    expiresAt: "תוקף",
    language: "שפה",
    fixture: "TEST ONLY — נתונים סינתטיים בלבד. אין להזין מידע בריאותי אמיתי.",
    download: "הורדת קובץ בדיקה סינתטי",
    file: "מסמך סינתטי (txt בלבד)",
    readCopy: "הנוסח ותשובת הבדיקה שהוגשו",
    history: "היסטוריית ההגשות נשמרת באופן מוגן. תיקון יוצר גרסה חדשה.",
    loading: "טוען…",
  },
  ar: {
    title: "الإقرار الصحي",
    unavailable: "جمع الإقرارات الصحية غير مفعّل. يمكن التواصل مع الاستوديو للدعم.",
    participant: "المشارك",
    send: "تأكيد وإرسال الاختبار",
    sending: "جارٍ الحفظ…",
    retry: "إعادة المحاولة",
    consent: "التأكيد مطلوب.",
    status: "حالة الإقرار",
    copy: "قراءة النسخة المقدمة",
    change: "الإبلاغ عن تغيير / تقديم نسخة جديدة",
    upload: "تحميل مستند اختبار اصطناعي",
    review: "مراجعة المستندات المصرّح بها",
    read: "قراءة المستند",
    accept: "قبول مستند الاختبار الذي تمت مراجعته",
    reject: "رفض مستند الاختبار",
    back: "العودة للحصة — التحقق من التوفر وتأكيد الحجز",
    saved: "أكد الخادم الاستلام. لم يتم حجز أو خصم.",
    error: "تعذر إتمام الإجراء. المسودة لا تزال هنا. يمكن إعادة المحاولة بأمان.",
    required: "يجب إكمال الإقرار الصحي قبل الحجز.",
    pending: "مراجعة المستند معلقة. التحميل وحده لا يمنح الأهلية.",
    choose: "اختيار المشارك",
    guardian: "يمكن فقط لوالد أو وصي تم التحقق منه التوقيع للطفل. يحتاج كل طفل إقرارًا منفصلاً.",
    draft: "مسودة — لم تقدم",
    missing: "غير موجود",
    submitted: "تم التقديم",
    requires_medical_document: "المستند مطلوب",
    pending_review: "قيد المراجعة",
    valid: "أهلية سارية (ليست تشخيصًا طبيًا)",
    expired: "منتهي الصلاحية",
    superseded: "مطلوب إقرار جديد",
    newVersion: "بدء إقرار اختبار جديد",
    empty: "لا توجد مستندات بانتظار المراجعة.",
    submittedAt: "وقت التقديم",
    expiresAt: "الصلاحية",
    language: "اللغة",
    fixture: "TEST ONLY — بيانات اصطناعية فقط. لا تدخل معلومات صحية حقيقية.",
    download: "تنزيل ملف اختبار اصطناعي",
    file: "مستند اصطناعي (txt فقط)",
    readCopy: "النص وإجابة الاختبار المقدمان",
    history: "يتم حفظ سجل التقديمات بأمان. التصحيح ينشئ نسخة جديدة.",
    loading: "جارٍ التحميل…",
  },
};
