export const onboardingCopy = {
  en: {
    title: "Your health declaration",
    studio: "Cloud & Core Studio",
    intro: "A little care before your first class.",
    paused:
      "The studio is preparing its health declaration. You do not need to submit medical information yet.",
    adult: "Members aged 18 and over complete and sign their own declaration.",
    parent:
      "You keep your account and manage your bookings. If you are under 18, a parent or legal guardian aged 18 or over completes your medical declaration.",
    verification:
      "The studio owner verifies the parent or guardian relationship before the declaration can be signed. Any required medical document also needs review before booking is available.",
    dob: "Date of birth",
    dobHelp:
      "This determines who signs your health declaration. Contact the studio if your recorded date needs correction.",
    invalidDob: "Enter a valid date of birth.",
    save: "Save date of birth",
    share: "Create a link for your parent",
    linkHelp:
      "Share this private link with your parent or legal guardian. It expires in 72 hours. Creating a new link replaces any unused link.",
    copied: "Link copied",
    copy: "Copy link",
    pending: "Waiting for the studio to verify your parent or guardian.",
    verified: "Your parent or guardian can now complete your declaration from their account.",
    expired: "Your parent link expired. Create a new link.",
    loading: "Loading…",
    retry: "Try again",
    error: "We could not complete this step. Please try again.",
    continue: "Continue to my account",
    notice:
      "Please complete your health declaration within 30 days. After that, a valid declaration is required for new bookings. Existing bookings remain in place.",
    acknowledge: "I have read this notice",
    grace: "Complete by",
    valid: "Your declaration is complete.",
    guardianTitle: "Parent or guardian declaration",
    signIn: "Sign in or create your own account to continue",
    guardianIntro:
      "Use your own adult account. The studio will verify your relationship before you can complete the member’s declaration.",
    relationship: "Your relationship",
    parentOption: "Parent",
    guardianOption: "Legal guardian",
    confirm: "I confirm I am this member’s parent or legal guardian and am at least 18 years old.",
    request: "Request verification",
    noLink: "Open the private link shared with you by the member.",
    queue: "Parent and guardian verification",
    ownerConfirm:
      "I have independently verified this adult’s identity and parent or legal guardian relationship.",
    approve: "Verify relationship",
    revoke: "Revoke relationship",
    noQueue: "No relationships awaiting review.",
    test: "Local testing uses fictional answers only.",
  },
  he: {
    title: "הצהרת הבריאות שלך",
    studio: "Cloud & Core Studio",
    intro: "קצת תשומת לב לפני השיעור הראשון.",
    paused: "הסטודיו מכין את הצהרת הבריאות. עדיין אין צורך למסור מידע רפואי.",
    adult: "מגיל 18 ממלאים וחותמים על ההצהרה באופן עצמאי.",
    parent:
      "החשבון וההזמנות נשארים בניהולך. מתחת לגיל 18, הורה או אפוטרופוס חוקי בגיל 18 ומעלה ממלא את הצהרת הבריאות עבורך.",
    verification:
      "בעלת הסטודיו מאמתת את הקשר להורה או לאפוטרופוס לפני החתימה. גם מסמך רפואי נדרש חייב לעבור בדיקה לפני שניתן להזמין שיעורים.",
    dob: "תאריך לידה",
    dobHelp: "התאריך קובע מי חותם על ההצהרה. לתיקון תאריך שנשמר, יש לפנות לסטודיו.",
    invalidDob: "יש להזין תאריך לידה תקין.",
    save: "שמירת תאריך לידה",
    share: "יצירת קישור להורה",
    linkHelp:
      "שתפו את הקישור הפרטי עם ההורה או האפוטרופוס. תוקפו 72 שעות. קישור חדש מחליף קישור שלא נוצל.",
    copied: "הקישור הועתק",
    copy: "העתקת קישור",
    pending: "ממתינים לאימות ההורה או האפוטרופוס על ידי הסטודיו.",
    verified: "ההורה או האפוטרופוס יכולים כעת למלא את ההצהרה מהחשבון שלהם.",
    expired: "תוקף הקישור פג. צרו קישור חדש.",
    loading: "בטעינה…",
    retry: "ניסיון נוסף",
    error: "לא ניתן להשלים את השלב. נסו שוב.",
    continue: "המשך לחשבון שלי",
    notice:
      "יש למלא הצהרת בריאות בתוך 30 יום. לאחר מכן תידרש הצהרה תקפה להזמנות חדשות. הזמנות קיימות נשמרות.",
    acknowledge: "קראתי את ההודעה",
    grace: "יש להשלים עד",
    valid: "ההצהרה שלך הושלמה.",
    guardianTitle: "הצהרת הורה או אפוטרופוס",
    signIn: "התחברו או צרו חשבון אישי להמשך",
    guardianIntro:
      "יש להשתמש בחשבון האישי של המבוגר. הסטודיו יאמת את הקשר לפני שניתן יהיה למלא את ההצהרה.",
    relationship: "הקשר למתאמנת",
    parentOption: "הורה",
    guardianOption: "אפוטרופוס חוקי",
    confirm: "אני מאשר/ת שאני ההורה או האפוטרופוס החוקי של המתאמנת ובגיל 18 ומעלה.",
    request: "בקשת אימות",
    noLink: "פתחו את הקישור הפרטי שהמתאמנת שיתפה איתכם.",
    queue: "אימות הורים ואפוטרופוסים",
    ownerConfirm: "אימתתי באופן עצמאי את זהות המבוגר ואת הקשר כהורה או כאפוטרופוס חוקי.",
    approve: "אימות הקשר",
    revoke: "ביטול הקשר",
    noQueue: "אין קשרים הממתינים לבדיקה.",
    test: "בדיקה מקומית עם תשובות בדיוניות בלבד.",
  },
  ar: {
    title: "إقرارك الصحي",
    studio: "Cloud & Core Studio",
    intro: "قليل من العناية قبل حصتك الأولى.",
    paused: "يُعدّ الاستوديو الإقرار الصحي. لا تحتاجين إلى تقديم معلومات طبية بعد.",
    adult: "المشتركات بعمر 18 عامًا أو أكثر يُكملن ويوقّعن إقرارهن بأنفسهن.",
    parent:
      "يبقى حسابك وحجوزاتك تحت إدارتك. إذا كنتِ دون 18 عامًا، يُكمل أحد الوالدين أو الوصي القانوني البالغ 18 عامًا أو أكثر إقرارك الطبي.",
    verification:
      "تتحقق مالكة الاستوديو من علاقة الوالد أو الوصي قبل التوقيع. وأي مستند طبي مطلوب يحتاج أيضًا إلى مراجعة قبل إتاحة الحجز.",
    dob: "تاريخ الميلاد",
    dobHelp: "يحدد هذا التاريخ من يوقّع الإقرار الصحي. تواصلي مع الاستوديو لتصحيح التاريخ المحفوظ.",
    invalidDob: "أدخلي تاريخ ميلاد صحيحًا.",
    save: "حفظ تاريخ الميلاد",
    share: "إنشاء رابط لولي الأمر",
    linkHelp:
      "شاركي هذا الرابط الخاص مع أحد الوالدين أو الوصي القانوني. تنتهي صلاحيته خلال 72 ساعة. الرابط الجديد يستبدل أي رابط لم يُستخدم.",
    copied: "تم نسخ الرابط",
    copy: "نسخ الرابط",
    pending: "بانتظار تحقق الاستوديو من الوالد أو الوصي.",
    verified: "يمكن للوالد أو الوصي الآن إكمال إقرارك من حسابه.",
    expired: "انتهت صلاحية الرابط. أنشئي رابطًا جديدًا.",
    loading: "جارٍ التحميل…",
    retry: "حاولي مجددًا",
    error: "تعذر إكمال هذه الخطوة. حاولي مجددًا.",
    continue: "المتابعة إلى حسابي",
    notice:
      "يرجى إكمال الإقرار الصحي خلال 30 يومًا. بعد ذلك، يلزم إقرار صالح للحجوزات الجديدة. تبقى الحجوزات الحالية كما هي.",
    acknowledge: "قرأت هذا الإشعار",
    grace: "أكملي قبل",
    valid: "اكتمل إقرارك.",
    guardianTitle: "إقرار الوالد أو الوصي",
    signIn: "سجّل الدخول أو أنشئ حسابك الخاص للمتابعة",
    guardianIntro:
      "استخدم حسابك الشخصي كشخص بالغ. يتحقق الاستوديو من علاقتك بالمشتركة قبل إتاحة إكمال إقرارها.",
    relationship: "علاقتك بالمشتركة",
    parentOption: "أحد الوالدين",
    guardianOption: "وصي قانوني",
    confirm: "أؤكد أنني أحد والدي المشتركة أو وصيّها القانوني وأن عمري 18 عامًا أو أكثر.",
    request: "طلب التحقق",
    noLink: "افتح الرابط الخاص الذي شاركته معك المشتركة.",
    queue: "التحقق من الوالدين والأوصياء",
    ownerConfirm: "تحققتُ بشكل مستقل من هوية هذا البالغ وعلاقته كوالد أو وصي قانوني.",
    approve: "توثيق العلاقة",
    revoke: "إلغاء العلاقة",
    noQueue: "لا توجد علاقات بانتظار المراجعة.",
    test: "الاختبار المحلي يستخدم إجابات افتراضية فقط.",
  },
};
