steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --no-cache
      - --build-arg
      - VITE_SUPABASE_PROJECT_ID=${_VITE_SUPABASE_PROJECT_ID}
      - --build-arg
      - VITE_SUPABASE_URL=${_VITE_SUPABASE_URL}
      - --build-arg
      - VITE_SUPABASE_PUBLISHABLE_KEY=${_VITE_SUPABASE_PUBLISHABLE_KEY}
      - --build-arg
      - VITE_APNS_ENV=${_VITE_APNS_ENV}
      - -t
      - ${_IMAGE}:$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE}:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - cloud-core-studio
      - --image
      - ${_IMAGE}:$COMMIT_SHA
      - --region
      - me-west1
      - --quiet

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - services
      - update-traffic
      - cloud-core-studio
      - --region
      - me-west1
      - --to-latest
      - --quiet

images:
  - ${_IMAGE}:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
