/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedMemberRouteRouteImport } from './routes/_authenticated/member/route'
import { Route as AuthenticatedInstructorRouteRouteImport } from './routes/_authenticated/instructor/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedMemberIndexRouteImport } from './routes/_authenticated/member/index'
import { Route as AuthenticatedInstructorIndexRouteImport } from './routes/_authenticated/instructor/index'
import { Route as AuthenticatedBookingsIndexRouteImport } from './routes/_authenticated/bookings/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedReceiptsIdRouteImport } from './routes/_authenticated/receipts/$id'
import { Route as AuthenticatedMemberScheduleRouteImport } from './routes/_authenticated/member/schedule'
import { Route as AuthenticatedMemberPackagesRouteImport } from './routes/_authenticated/member/packages'
import { Route as AuthenticatedMemberBookingsRouteImport } from './routes/_authenticated/member/bookings'
import { Route as AuthenticatedMemberAccountRouteImport } from './routes/_authenticated/member/account'
import { Route as AuthenticatedBookingsIdRouteImport } from './routes/_authenticated/bookings/$id'
import { Route as AuthenticatedAdminTemplatesRouteImport } from './routes/_authenticated/admin/templates'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminScheduleRouteImport } from './routes/_authenticated/admin/schedule'
import { Route as AuthenticatedAdminRoomsRouteImport } from './routes/_authenticated/admin/rooms'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminPulseRouteImport } from './routes/_authenticated/admin/pulse'
import { Route as AuthenticatedAdminProgramsRouteImport } from './routes/_authenticated/admin/programs'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin/plans'
import { Route as AuthenticatedAdminPlannerRouteImport } from './routes/_authenticated/admin/planner'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin/messages'
import { Route as AuthenticatedAdminInstructorsRouteImport } from './routes/_authenticated/admin/instructors'
import { Route as AuthenticatedAdminCreditsRouteImport } from './routes/_authenticated/admin/credits'
import { Route as AuthenticatedAdminCalendarRouteImport } from './routes/_authenticated/admin/calendar'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin/bookings'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminAttendanceRouteImport } from './routes/_authenticated/admin/attendance'
import { Route as AuthenticatedAdminMembersIndexRouteImport } from './routes/_authenticated/admin/members/index'
import { Route as AuthenticatedAdminClassesIndexRouteImport } from './routes/_authenticated/admin/classes/index'
import { Route as AuthenticatedAdminMembersIdRouteImport } from './routes/_authenticated/admin/members/$id'
import { Route as AuthenticatedAdminClassesNewRouteImport } from './routes/_authenticated/admin/classes/new'
import { Route as AuthenticatedAdminClassesIdRouteImport } from './routes/_authenticated/admin/classes/$id'
import { Route as ApiPublicWebhooksPaymentsProviderRouteImport } from './routes/api/public/webhooks/payments.$provider'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemberRouteRoute =
  AuthenticatedMemberRouteRouteImport.update({
    id: '/member',
    path: '/member',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstructorRouteRoute =
  AuthenticatedInstructorRouteRouteImport.update({
    id: '/instructor',
    path: '/instructor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemberIndexRoute =
  AuthenticatedMemberIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMemberRouteRoute,
  } as any)
const AuthenticatedInstructorIndexRoute =
  AuthenticatedInstructorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInstructorRouteRoute,
  } as any)
const AuthenticatedBookingsIndexRoute =
  AuthenticatedBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedReceiptsIdRoute = AuthenticatedReceiptsIdRouteImport.update({
  id: '/receipts/$id',
  path: '/receipts/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemberScheduleRoute =
  AuthenticatedMemberScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedMemberRouteRoute,
  } as any)
const AuthenticatedMemberPackagesRoute =
  AuthenticatedMemberPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedMemberRouteRoute,
  } as any)
const AuthenticatedMemberBookingsRoute =
  AuthenticatedMemberBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedMemberRouteRoute,
  } as any)
const AuthenticatedMemberAccountRoute =
  AuthenticatedMemberAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedMemberRouteRoute,
  } as any)
const AuthenticatedBookingsIdRoute = AuthenticatedBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTemplatesRoute =
  AuthenticatedAdminTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminScheduleRoute =
  AuthenticatedAdminScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRoomsRoute = AuthenticatedAdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPulseRoute = AuthenticatedAdminPulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminProgramsRoute =
  AuthenticatedAdminProgramsRouteImport.update({
    id: '/programs',
    path: '/programs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPlannerRoute =
  AuthenticatedAdminPlannerRouteImport.update({
    id: '/planner',
    path: '/planner',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminInstructorsRoute =
  AuthenticatedAdminInstructorsRouteImport.update({
    id: '/instructors',
    path: '/instructors',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCreditsRoute =
  AuthenticatedAdminCreditsRouteImport.update({
    id: '/credits',
    path: '/credits',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCalendarRoute =
  AuthenticatedAdminCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAttendanceRoute =
  AuthenticatedAdminAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMembersIndexRoute =
  AuthenticatedAdminMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClassesIndexRoute =
  AuthenticatedAdminClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMembersIdRoute =
  AuthenticatedAdminMembersIdRouteImport.update({
    id: '/members/$id',
    path: '/members/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClassesNewRoute =
  AuthenticatedAdminClassesNewRouteImport.update({
    id: '/classes/new',
    path: '/classes/new',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClassesIdRoute =
  AuthenticatedAdminClassesIdRouteImport.update({
    id: '/classes/$id',
    path: '/classes/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicWebhooksPaymentsProviderRoute =
  ApiPublicWebhooksPaymentsProviderRouteImport.update({
    id: '/api/public/webhooks/payments/$provider',
    path: '/api/public/webhooks/payments/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/instructor': typeof AuthenticatedInstructorRouteRouteWithChildren
  '/member': typeof AuthenticatedMemberRouteRouteWithChildren
  '/plans': typeof AuthenticatedPlansRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/credits': typeof AuthenticatedAdminCreditsRoute
  '/admin/instructors': typeof AuthenticatedAdminInstructorsRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/planner': typeof AuthenticatedAdminPlannerRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/admin/pulse': typeof AuthenticatedAdminPulseRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/rooms': typeof AuthenticatedAdminRoomsRoute
  '/admin/schedule': typeof AuthenticatedAdminScheduleRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/member/account': typeof AuthenticatedMemberAccountRoute
  '/member/bookings': typeof AuthenticatedMemberBookingsRoute
  '/member/packages': typeof AuthenticatedMemberPackagesRoute
  '/member/schedule': typeof AuthenticatedMemberScheduleRoute
  '/receipts/$id': typeof AuthenticatedReceiptsIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/instructor/': typeof AuthenticatedInstructorIndexRoute
  '/member/': typeof AuthenticatedMemberIndexRoute
  '/admin/classes/$id': typeof AuthenticatedAdminClassesIdRoute
  '/admin/classes/new': typeof AuthenticatedAdminClassesNewRoute
  '/admin/members/$id': typeof AuthenticatedAdminMembersIdRoute
  '/admin/classes/': typeof AuthenticatedAdminClassesIndexRoute
  '/admin/members/': typeof AuthenticatedAdminMembersIndexRoute
  '/api/public/webhooks/payments/$provider': typeof ApiPublicWebhooksPaymentsProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/credits': typeof AuthenticatedAdminCreditsRoute
  '/admin/instructors': typeof AuthenticatedAdminInstructorsRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/planner': typeof AuthenticatedAdminPlannerRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/admin/pulse': typeof AuthenticatedAdminPulseRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/rooms': typeof AuthenticatedAdminRoomsRoute
  '/admin/schedule': typeof AuthenticatedAdminScheduleRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/member/account': typeof AuthenticatedMemberAccountRoute
  '/member/bookings': typeof AuthenticatedMemberBookingsRoute
  '/member/packages': typeof AuthenticatedMemberPackagesRoute
  '/member/schedule': typeof AuthenticatedMemberScheduleRoute
  '/receipts/$id': typeof AuthenticatedReceiptsIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
  '/instructor': typeof AuthenticatedInstructorIndexRoute
  '/member': typeof AuthenticatedMemberIndexRoute
  '/admin/classes/$id': typeof AuthenticatedAdminClassesIdRoute
  '/admin/classes/new': typeof AuthenticatedAdminClassesNewRoute
  '/admin/members/$id': typeof AuthenticatedAdminMembersIdRoute
  '/admin/classes': typeof AuthenticatedAdminClassesIndexRoute
  '/admin/members': typeof AuthenticatedAdminMembersIndexRoute
  '/api/public/webhooks/payments/$provider': typeof ApiPublicWebhooksPaymentsProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/instructor': typeof AuthenticatedInstructorRouteRouteWithChildren
  '/_authenticated/member': typeof AuthenticatedMemberRouteRouteWithChildren
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/_authenticated/admin/credits': typeof AuthenticatedAdminCreditsRoute
  '/_authenticated/admin/instructors': typeof AuthenticatedAdminInstructorsRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/planner': typeof AuthenticatedAdminPlannerRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/_authenticated/admin/pulse': typeof AuthenticatedAdminPulseRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/rooms': typeof AuthenticatedAdminRoomsRoute
  '/_authenticated/admin/schedule': typeof AuthenticatedAdminScheduleRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/_authenticated/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/_authenticated/member/account': typeof AuthenticatedMemberAccountRoute
  '/_authenticated/member/bookings': typeof AuthenticatedMemberBookingsRoute
  '/_authenticated/member/packages': typeof AuthenticatedMemberPackagesRoute
  '/_authenticated/member/schedule': typeof AuthenticatedMemberScheduleRoute
  '/_authenticated/receipts/$id': typeof AuthenticatedReceiptsIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/_authenticated/instructor/': typeof AuthenticatedInstructorIndexRoute
  '/_authenticated/member/': typeof AuthenticatedMemberIndexRoute
  '/_authenticated/admin/classes/$id': typeof AuthenticatedAdminClassesIdRoute
  '/_authenticated/admin/classes/new': typeof AuthenticatedAdminClassesNewRoute
  '/_authenticated/admin/members/$id': typeof AuthenticatedAdminMembersIdRoute
  '/_authenticated/admin/classes/': typeof AuthenticatedAdminClassesIndexRoute
  '/_authenticated/admin/members/': typeof AuthenticatedAdminMembersIndexRoute
  '/api/public/webhooks/payments/$provider': typeof ApiPublicWebhooksPaymentsProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/instructor'
    | '/member'
    | '/plans'
    | '/schedule'
    | '/studio'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/credits'
    | '/admin/instructors'
    | '/admin/messages'
    | '/admin/payments'
    | '/admin/planner'
    | '/admin/plans'
    | '/admin/programs'
    | '/admin/pulse'
    | '/admin/reports'
    | '/admin/rooms'
    | '/admin/schedule'
    | '/admin/settings'
    | '/admin/templates'
    | '/bookings/$id'
    | '/member/account'
    | '/member/bookings'
    | '/member/packages'
    | '/member/schedule'
    | '/receipts/$id'
    | '/admin/'
    | '/bookings/'
    | '/instructor/'
    | '/member/'
    | '/admin/classes/$id'
    | '/admin/classes/new'
    | '/admin/members/$id'
    | '/admin/classes/'
    | '/admin/members/'
    | '/api/public/webhooks/payments/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/plans'
    | '/schedule'
    | '/studio'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/credits'
    | '/admin/instructors'
    | '/admin/messages'
    | '/admin/payments'
    | '/admin/planner'
    | '/admin/plans'
    | '/admin/programs'
    | '/admin/pulse'
    | '/admin/reports'
    | '/admin/rooms'
    | '/admin/schedule'
    | '/admin/settings'
    | '/admin/templates'
    | '/bookings/$id'
    | '/member/account'
    | '/member/bookings'
    | '/member/packages'
    | '/member/schedule'
    | '/receipts/$id'
    | '/admin'
    | '/bookings'
    | '/instructor'
    | '/member'
    | '/admin/classes/$id'
    | '/admin/classes/new'
    | '/admin/members/$id'
    | '/admin/classes'
    | '/admin/members'
    | '/api/public/webhooks/payments/$provider'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/instructor'
    | '/_authenticated/member'
    | '/_authenticated/plans'
    | '/_authenticated/schedule'
    | '/_authenticated/studio'
    | '/_authenticated/admin/attendance'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/calendar'
    | '/_authenticated/admin/credits'
    | '/_authenticated/admin/instructors'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/planner'
    | '/_authenticated/admin/plans'
    | '/_authenticated/admin/programs'
    | '/_authenticated/admin/pulse'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/rooms'
    | '/_authenticated/admin/schedule'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/templates'
    | '/_authenticated/bookings/$id'
    | '/_authenticated/member/account'
    | '/_authenticated/member/bookings'
    | '/_authenticated/member/packages'
    | '/_authenticated/member/schedule'
    | '/_authenticated/receipts/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/bookings/'
    | '/_authenticated/instructor/'
    | '/_authenticated/member/'
    | '/_authenticated/admin/classes/$id'
    | '/_authenticated/admin/classes/new'
    | '/_authenticated/admin/members/$id'
    | '/_authenticated/admin/classes/'
    | '/_authenticated/admin/members/'
    | '/api/public/webhooks/payments/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicWebhooksPaymentsProviderRoute: typeof ApiPublicWebhooksPaymentsProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/member': {
      id: '/_authenticated/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof AuthenticatedMemberRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instructor': {
      id: '/_authenticated/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof AuthenticatedInstructorRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/member/': {
      id: '/_authenticated/member/'
      path: '/'
      fullPath: '/member/'
      preLoaderRoute: typeof AuthenticatedMemberIndexRouteImport
      parentRoute: typeof AuthenticatedMemberRouteRoute
    }
    '/_authenticated/instructor/': {
      id: '/_authenticated/instructor/'
      path: '/'
      fullPath: '/instructor/'
      preLoaderRoute: typeof AuthenticatedInstructorIndexRouteImport
      parentRoute: typeof AuthenticatedInstructorRouteRoute
    }
    '/_authenticated/bookings/': {
      id: '/_authenticated/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthenticatedBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/receipts/$id': {
      id: '/_authenticated/receipts/$id'
      path: '/receipts/$id'
      fullPath: '/receipts/$id'
      preLoaderRoute: typeof AuthenticatedReceiptsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/member/schedule': {
      id: '/_authenticated/member/schedule'
      path: '/schedule'
      fullPath: '/member/schedule'
      preLoaderRoute: typeof AuthenticatedMemberScheduleRouteImport
      parentRoute: typeof AuthenticatedMemberRouteRoute
    }
    '/_authenticated/member/packages': {
      id: '/_authenticated/member/packages'
      path: '/packages'
      fullPath: '/member/packages'
      preLoaderRoute: typeof AuthenticatedMemberPackagesRouteImport
      parentRoute: typeof AuthenticatedMemberRouteRoute
    }
    '/_authenticated/member/bookings': {
      id: '/_authenticated/member/bookings'
      path: '/bookings'
      fullPath: '/member/bookings'
      preLoaderRoute: typeof AuthenticatedMemberBookingsRouteImport
      parentRoute: typeof AuthenticatedMemberRouteRoute
    }
    '/_authenticated/member/account': {
      id: '/_authenticated/member/account'
      path: '/account'
      fullPath: '/member/account'
      preLoaderRoute: typeof AuthenticatedMemberAccountRouteImport
      parentRoute: typeof AuthenticatedMemberRouteRoute
    }
    '/_authenticated/bookings/$id': {
      id: '/_authenticated/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof AuthenticatedBookingsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/templates': {
      id: '/_authenticated/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/schedule': {
      id: '/_authenticated/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AuthenticatedAdminScheduleRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/rooms': {
      id: '/_authenticated/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AuthenticatedAdminRoomsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pulse': {
      id: '/_authenticated/admin/pulse'
      path: '/pulse'
      fullPath: '/admin/pulse'
      preLoaderRoute: typeof AuthenticatedAdminPulseRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/programs': {
      id: '/_authenticated/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AuthenticatedAdminProgramsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/planner': {
      id: '/_authenticated/admin/planner'
      path: '/planner'
      fullPath: '/admin/planner'
      preLoaderRoute: typeof AuthenticatedAdminPlannerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/instructors': {
      id: '/_authenticated/admin/instructors'
      path: '/instructors'
      fullPath: '/admin/instructors'
      preLoaderRoute: typeof AuthenticatedAdminInstructorsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/credits': {
      id: '/_authenticated/admin/credits'
      path: '/credits'
      fullPath: '/admin/credits'
      preLoaderRoute: typeof AuthenticatedAdminCreditsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/calendar': {
      id: '/_authenticated/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AuthenticatedAdminCalendarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/attendance': {
      id: '/_authenticated/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AuthenticatedAdminAttendanceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/members/': {
      id: '/_authenticated/admin/members/'
      path: '/members'
      fullPath: '/admin/members/'
      preLoaderRoute: typeof AuthenticatedAdminMembersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/classes/': {
      id: '/_authenticated/admin/classes/'
      path: '/classes'
      fullPath: '/admin/classes/'
      preLoaderRoute: typeof AuthenticatedAdminClassesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/members/$id': {
      id: '/_authenticated/admin/members/$id'
      path: '/members/$id'
      fullPath: '/admin/members/$id'
      preLoaderRoute: typeof AuthenticatedAdminMembersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/classes/new': {
      id: '/_authenticated/admin/classes/new'
      path: '/classes/new'
      fullPath: '/admin/classes/new'
      preLoaderRoute: typeof AuthenticatedAdminClassesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/classes/$id': {
      id: '/_authenticated/admin/classes/$id'
      path: '/classes/$id'
      fullPath: '/admin/classes/$id'
      preLoaderRoute: typeof AuthenticatedAdminClassesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/webhooks/payments/$provider': {
      id: '/api/public/webhooks/payments/$provider'
      path: '/api/public/webhooks/payments/$provider'
      fullPath: '/api/public/webhooks/payments/$provider'
      preLoaderRoute: typeof ApiPublicWebhooksPaymentsProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAttendanceRoute: typeof AuthenticatedAdminAttendanceRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminCalendarRoute: typeof AuthenticatedAdminCalendarRoute
  AuthenticatedAdminCreditsRoute: typeof AuthenticatedAdminCreditsRoute
  AuthenticatedAdminInstructorsRoute: typeof AuthenticatedAdminInstructorsRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPlannerRoute: typeof AuthenticatedAdminPlannerRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedAdminProgramsRoute: typeof AuthenticatedAdminProgramsRoute
  AuthenticatedAdminPulseRoute: typeof AuthenticatedAdminPulseRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminRoomsRoute: typeof AuthenticatedAdminRoomsRoute
  AuthenticatedAdminScheduleRoute: typeof AuthenticatedAdminScheduleRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTemplatesRoute: typeof AuthenticatedAdminTemplatesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminClassesIdRoute: typeof AuthenticatedAdminClassesIdRoute
  AuthenticatedAdminClassesNewRoute: typeof AuthenticatedAdminClassesNewRoute
  AuthenticatedAdminMembersIdRoute: typeof AuthenticatedAdminMembersIdRoute
  AuthenticatedAdminClassesIndexRoute: typeof AuthenticatedAdminClassesIndexRoute
  AuthenticatedAdminMembersIndexRoute: typeof AuthenticatedAdminMembersIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAttendanceRoute: AuthenticatedAdminAttendanceRoute,
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
    AuthenticatedAdminCalendarRoute: AuthenticatedAdminCalendarRoute,
    AuthenticatedAdminCreditsRoute: AuthenticatedAdminCreditsRoute,
    AuthenticatedAdminInstructorsRoute: AuthenticatedAdminInstructorsRoute,
    AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminPlannerRoute: AuthenticatedAdminPlannerRoute,
    AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
    AuthenticatedAdminProgramsRoute: AuthenticatedAdminProgramsRoute,
    AuthenticatedAdminPulseRoute: AuthenticatedAdminPulseRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminRoomsRoute: AuthenticatedAdminRoomsRoute,
    AuthenticatedAdminScheduleRoute: AuthenticatedAdminScheduleRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminTemplatesRoute: AuthenticatedAdminTemplatesRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminClassesIdRoute: AuthenticatedAdminClassesIdRoute,
    AuthenticatedAdminClassesNewRoute: AuthenticatedAdminClassesNewRoute,
    AuthenticatedAdminMembersIdRoute: AuthenticatedAdminMembersIdRoute,
    AuthenticatedAdminClassesIndexRoute: AuthenticatedAdminClassesIndexRoute,
    AuthenticatedAdminMembersIndexRoute: AuthenticatedAdminMembersIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedInstructorRouteRouteChildren {
  AuthenticatedInstructorIndexRoute: typeof AuthenticatedInstructorIndexRoute
}

const AuthenticatedInstructorRouteRouteChildren: AuthenticatedInstructorRouteRouteChildren =
  {
    AuthenticatedInstructorIndexRoute: AuthenticatedInstructorIndexRoute,
  }

const AuthenticatedInstructorRouteRouteWithChildren =
  AuthenticatedInstructorRouteRoute._addFileChildren(
    AuthenticatedInstructorRouteRouteChildren,
  )

interface AuthenticatedMemberRouteRouteChildren {
  AuthenticatedMemberAccountRoute: typeof AuthenticatedMemberAccountRoute
  AuthenticatedMemberBookingsRoute: typeof AuthenticatedMemberBookingsRoute
  AuthenticatedMemberPackagesRoute: typeof AuthenticatedMemberPackagesRoute
  AuthenticatedMemberScheduleRoute: typeof AuthenticatedMemberScheduleRoute
  AuthenticatedMemberIndexRoute: typeof AuthenticatedMemberIndexRoute
}

const AuthenticatedMemberRouteRouteChildren: AuthenticatedMemberRouteRouteChildren =
  {
    AuthenticatedMemberAccountRoute: AuthenticatedMemberAccountRoute,
    AuthenticatedMemberBookingsRoute: AuthenticatedMemberBookingsRoute,
    AuthenticatedMemberPackagesRoute: AuthenticatedMemberPackagesRoute,
    AuthenticatedMemberScheduleRoute: AuthenticatedMemberScheduleRoute,
    AuthenticatedMemberIndexRoute: AuthenticatedMemberIndexRoute,
  }

const AuthenticatedMemberRouteRouteWithChildren =
  AuthenticatedMemberRouteRoute._addFileChildren(
    AuthenticatedMemberRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedInstructorRouteRoute: typeof AuthenticatedInstructorRouteRouteWithChildren
  AuthenticatedMemberRouteRoute: typeof AuthenticatedMemberRouteRouteWithChildren
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedBookingsIdRoute: typeof AuthenticatedBookingsIdRoute
  AuthenticatedReceiptsIdRoute: typeof AuthenticatedReceiptsIdRoute
  AuthenticatedBookingsIndexRoute: typeof AuthenticatedBookingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedInstructorRouteRoute:
    AuthenticatedInstructorRouteRouteWithChildren,
  AuthenticatedMemberRouteRoute: AuthenticatedMemberRouteRouteWithChildren,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedBookingsIdRoute: AuthenticatedBookingsIdRoute,
  AuthenticatedReceiptsIdRoute: AuthenticatedReceiptsIdRoute,
  AuthenticatedBookingsIndexRoute: AuthenticatedBookingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicWebhooksPaymentsProviderRoute:
    ApiPublicWebhooksPaymentsProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
