// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";

const PUBLIC_APP_MARKETING_PATH = /^\/app\/(?:ar|he|en)\/?$/;

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    if (typeof window !== "undefined" && PUBLIC_APP_MARKETING_PATH.test(window.location.pathname)) {
      return next();
    }

    const { supabase } = await import("./client");
    const { data } = await supabase.auth.getSession();
    const token = data.session?.access_token;
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
